apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:vijayprabhu04/argocd-configuration.git
    targetRevision: main
    path: apps
    directory:
      recurse: true
  destination: 
    server: https://kubernetes.default.svc
    namespace: applications

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true