apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-applications
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:vijayprabhu04/argocd-configuration.git
    targetRevision: deployments
    directory:
      recurse: true
  destination: 
    server: https://kubernetes.default.svc
    namespace: development

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true